# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e37329f90775b52a3b8cc5143bf439a99d62b1baf9a45e650f9e6233417c51a887cbe0ea19ec287eadb978531642a32e3c1cc918b76120ad885643a537db8d4b

test:
  secret_key_base: 50415cc061efecac8fd23f6b3e3480ab6ea5a3d4283a4e9bafc44de96e33ad3e48650883a2c37555448842153e3278e3a00937b11ca05c6e64fbdb3ac4d1cad3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
